# docker-compose up
# docker-compose run web rake db:migrate db:seed
#
version: '3.6'
services:
  web:
    build: .
    depends_on:
      - crdb
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DBHOST: crdb
      DBUSER: dev
  crdb:
   image: cockroachdb/cockroach:v22.1.7
   ports:
     - "26257:26257"
     - "8080:8080"
   command: start-single-node --insecure
   volumes:
     - "database:/cockroach/cockroach-data"
volumes:
  database:
